# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7692bc9af5149e6095f649cf4dd2506c7c894050013608748ce9466de69219525b6597a7c2a483e1c1fbaa8987932d06e7f3940deac1e6bde367e6a3262e8cf9

test:
  secret_key_base: 60561c65a6ac33b83bcdb3b06a12146e94365ba80014bf71ebe046a13c279cb26863948f8946e0659363e3f92cb219cb919c9732d2dd1cd5f8b2982338ea4eff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
